include:
- project: iiidevops-templates/ci-template
  ref: v2.13.3
  file: ci/template.gitlab-ci.yml
- local: iiidevops/jobs/*.yml

stages:
- initial
- scan
- build
- deploy
- test
- userjobs

Test--SonarQube source code scan:
  variables:
    iiidevops: sonarqube
    CHART_TYPE: maven
    CHART_MAVEN_TAG: 3.6.3-openjdk-17

Test--Semgrep SAST code scan:
  variables:
    iiidevops: semgrep
    SEARCH_MAX_DEPTH: 20
    SAST_EXCLUDED_PATHS: "spec, test, tests, tmp, iiidevops, **/*.md"

Test--Anchore SBOM source code scan:
  variables:
    iiidevops: anchore-code

Test--Check-CN scan:
  variables:
    iiidevops: checkcn

Test--Checkmarx source code scan:
  variables:
    iiidevops: checkmarx
  
Build image:
  variables:
    iiidevops: build
    DOCKERFILE_PATH: Dockerfile
  
Build--Scan docker image:
  variables:
    iiidevops: build
  
Deploy--Set environment and wait deployment:
  variables:
    iiidevops: deploy
  
Deploy--Web:
  variables:
    iiidevops: deploy
    CHART_WEB_PORT: 8080
    CHART_PROXY_BODY_SIZE: 1m
    CHART_VOLUME_ENABLED: 'false'
    CHART_VOLUME_PATH: /usr/src
  
Test--Anchore SBOM:
  variables:
    iiidevops: anchore
  
Test--ZAP:
  variables:
    iiidevops: zap
    CHART_WEB_PORT: 8080
  
Test--WebInspect:
  variables:
    iiidevops: webinspect
  
Test--Postman:
  variables:
    iiidevops: postman
    CHART_WEB_PORT: 8080
  
Test--Sideex:
  variables:
    iiidevops: sideex
    CHART_WEB_PORT: 8080
  
